### ISSUE TITLE
Enable labels

### ISSUE THREAD

**Issue by tumf** [tumf/ansible-role-newrelic#2]
```
  roles:
    - role: tumf.newrelic
      newrelic_labels:
        - key1: var1
        - key2: var2
        - key3: var3
```
